version: 'build-{build}-{branch}'

platform: x64

build:
  parallel: true

image:
  - Visual Studio 2017

environment:
  # Create expected SHELL variable for pipenv.
  SHELL: "windows"
  CTEST_OUTPUT_ON_FAILURE: "1"
  matrix:
    - GENERATOR: "MSYS Makefiles"
      BUILDFLAGS: "VERBOSE=1"
      CMAKEARGS: ""
    - GENERATOR: "Visual Studio 15 2017 Win64"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: ""
    - GENERATOR: "Ninja"
      BUILDFLAGS: "-v"
      CMAKEARGS: ""
    - GENERATOR: "MSYS Makefiles"
      ANACONDA_TESTS_ONLY: "1"
      BUILDFLAGS: "VERBOSE=1"
      CMAKEARGS: ""
    - GENERATOR: "Visual Studio 15 2017 Win64"
      ANACONDA_TESTS_ONLY: "1"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: ""

#matrix:
#  fast_finish: true

init:
  - set PATH=C:\msys64\MINGW64\bin;C:\msys64\usr\bin;%PATH%
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
  # Remove Python 2.7 from path
  - set PATH=%PATH:C:\Python27;=%
  - set PATH=%PATH:C:\Python27\Scripts;=%
  # Add Anaconda to PATH
  - set PATH=C:\Deps\conda\Scripts;C:\Deps\conda\library\bin;%PATH%
  # Add system Boost to PATH, but only for VS generator
  - if "%GENERATOR%"=="Visual Studio 15 2017 Win64" (
      set PATH=C:\Libraries\boost_1_67_0\lib64-msvc-14.1;%PATH%
    )

cache:
  - c:\tools\vcpkg\installed\ -> testing\dependencies\appveyor\install.bat
  - c:\msys64\var\cache\pacman\pkg -> testing\dependencies\appveyor\install.bat
  - c:\Deps\conda\ -> testing\dependencies\appveyor\anaconda.ps1

install:
  - python -m pip install pipenv
  - '%APPVEYOR_BUILD_FOLDER%\testing\dependencies\appveyor\install.bat'
  - ps: .$env:APPVEYOR_BUILD_FOLDER\testing\dependencies\appveyor\anaconda.ps1
  - ps: .$env:APPVEYOR_BUILD_FOLDER\testing\dependencies\appveyor\install-msmpi.ps1

# extract step has to happen before the sh.exe workaround otherwise 7z will complain
before_build:
  - python --version
  - cmake --version
  - cd C:\projects
  - appveyor DownloadFile https://github.com/dev-cafe/cmake-cookbook/archive/%APPVEYOR_REPO_COMMIT%.zip
  - '%APPVEYOR_BUILD_FOLDER%\testing\dependencies\appveyor\extract.bat'

# the pipenv lock was added as workaround for pipenv complaining about wrong checksum
# after upgrade to Python 3.7 on Appveyor
build_script:
  - bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv lock"
  - bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv install"
  - bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-09/recipe-04'"
  - bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-04/recipe-04'"
  - if "%ANACONDA_TESTS_ONLY%"=="1" (
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-11/recipe-04'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-11/recipe-05'"
    ) else (
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-01/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-02/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-03/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-04/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-05/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-06/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-07/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-09/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-10/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-11/recipe-01'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-12/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-13/recipe-*'"
    )
#     bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-11/recipe-0[2-3]'" &&

deploy: off
