# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

# Speeding up a Visual Studio build.
# http://blogs.msdn.com/b/vcblog/archive/2011/01/05/damn-my-vc-project-is-building-slower-in-vs2010-what-do-i-do-now-a-step-by-step-guide.aspx
version: 'build_{build}-{branch}'

platform: x86

build:
  parallel: true

cache: c:\tools\vcpkg\installed\

environment:
  # Create expected SHELL variable for pipenv.
  SHELL: "windows"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "MinGW Makefiles"
      BUILDFLAGS: "VERBOSE=1"
      CMAKARGS: ""
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Ninja"
      BUILDFLAGS: "-v"
      CMAKARGS: ""
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"

init:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - ps: >-
      if (($env:GENERATOR -eq "MinGW Makefiles") -or ($env:GENERATOR -eq "Ninja")) {
        $env:PATH += ";C:\MinGW\bin"
      }
  - set PYTHONIOENCODING=utf-8
  - set PATH=C:\Users\AppVeyor\AppData\Roaming\Python\Scripts;%PATH%
  - set PATH=%PATH%;C:\projects\deps\ninja
  - set PATH=%PATH%;C:\Libraries\boost_1_63_0;C:\Libraries\boost_1_64_0
  - set PATH=%PATH%;C:\tools\vcpkg

install:
  - ps: .\testing\install.ps1
  - cd %APPVEYOR_BUILD_FOLDER%
  - pipenv install
  - pipenv run python --version

before_build:
  - cmake --version
  - ninja.exe --version

build_script:
  - pipenv run python testing\collect_tests.py Chapter01/recipe-*

deploy: off
