pipeline:
  build:
    image: robertodr/ubuntu-16.04_pgi17.4_hdf5:latest
    commands:
      - pip install --user pipenv --upgrade
      - pipenv install
      - ./testing/dependencies/report_versions.sh
      - pipenv run python testing/collect_tests.py 'chapter-*/recipe-*'

matrix:
  include:
    - GENERATOR: 'Unix Makefiles'
      BUILDFLAGS: 'VERBOSE=1'
    - GENERATOR: 'Ninja'
      BUILDFLAGS: '-v'
