pipeline:
  build:
    image: robertodr/ubuntu-16.04_pgi17.4_hdf5:latest
    commands:
      - virtualenv venv
      - . venv/bin/activate
      - pip install -r requirements.txt
      - ./dependencies/report_versions.sh
      - python .scripts/ci_configure_build_test.py 'Chapter*/recipe-*'

matrix:
  include:
    - GENERATOR: 'Unix Makefiles'
      BUILDFLAGS: 'VERBOSE=1'
    - GENERATOR: 'Ninja'
      BUILDFLAGS: '-v'

