language: cpp
sudo: false
dist: trusty
matrix:
  include:
    - os: linux
      addons: &1
        apt:
          packages:
            - gfortran
            - python-dev
            - libatlas-dev
            - liblapack-dev
            - liblapacke-dev
            - libopenmpi-dev
            - openmpi-bin
            - libboost1.55-all-dev
            - uuid-dev
            - pkg-config
      env:
        - GENERATOR="Unix Makefiles"
        - BUILDFLAGS="VERBOSE=1"
        - LC_ALL="en_US.UTF-8"
        - LANG="en_US.UTF-8"
        - LANGUAGE="en_US.UTF-8"
        - PYTHONIOENCODING=UTF-8
    - os: linux
      addons: *1
      env:
        - GENERATOR="Ninja"
        - BUILDFLAGS="-v"
        - LC_ALL="en_US.UTF-8"
        - LANG="en_US.UTF-8"
        - LANGUAGE="en_US.UTF-8"
        - PYTHONIOENCODING=UTF-8
    - os: osx
      env:
        - GENERATOR="Unix Makefiles"
        - BUILDFLAGS="VERBOSE=1"
    - os: osx
      env:
        - GENERATOR="Ninja"
        - BUILDFLAGS="-v"

cache:
  pip: true
  directories:
    - $HOME/Deps/cmake
    - $HOME/Deps/eigen
    - $HOME/Deps/hdf5
    - $HOME/Deps/ninja

env:
  global:
    - PATH=$HOME/Deps/cmake/bin:$HOME/Deps/ninja${PATH:+:$PATH}
    - LD_LIBRARY_PATH=$HOME/Deps/hdf5/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

before_install:
  # Dependencies are downloaded in $HOME/Downloads and installed in $HOME/Deps
  - mkdir -p $HOME/Downloads $HOME/Deps

install:
  - ./.scripts/install_deps.sh
  - ls $HOME/Deps/cmake
  - ls $HOME/Deps/eigen
  - ls $HOME/Deps/hdf5
  - ls $HOME/Deps/ninja
  - echo $PATH
  - echo $LD_LIBRARY_PATH
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

before_script:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - test -n $FC && unset FC

script:
  - ./.scripts/report_versions.sh
  - python .scripts/ci_configure_build_test.py 'Chapter*/recipe-*' --verbose
